name: auto-merge

on:
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.pull_request.title, '[auto merge] ') }}
    steps:
      - name: Generate apps token
        id: generate_token
        uses: tibdex/github-app-token@v1

      - name: Enable Pull Request Auto merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ github.event.number }}

      - name: Approve
        uses: hmarr/auto-approve-action@v2
        with:
          pull-request-number: ${{ github.event.number }}